document.write("<table>")
document.write(" <tbody><tr class=\"atwiki_tr_odd atwiki_tr_1\">		<td rowspan=\"2\" style=\"background-color:#CFC;vertical-align:MIDDLE;\">物品名</td>")
document.write("<td rowspan=\"2\" style=\"background-color:#CFC;vertical-align:MIDDLE;\">分類</td>")
document.write("<td rowspan=\"2\" style=\"background-color:#CFC;vertical-align:MIDDLE;\">料理能力&amp;使用效果</td>")
document.write("<td style=\"background-color:#CFC;text-align:center;\" colspan=\"5\">料理效果</td>")
document.write("<td style=\"background-color:#CFC;text-align:center;\" colspan=\"5\">物品效果</td>")
document.write("<td style=\"background-color:#CFC;text-align:center;\">堆疊數</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_2\">")
document.write("<td style=\"\">1★</td>")
document.write("<td style=\"\">2★</td>")
document.write("<td style=\"\">3★</td>")
document.write("<td style=\"\">4★</td>")
document.write("<td style=\"\">5★</td>")
document.write("<td style=\"\">1★</td>")
document.write("<td style=\"\">2★</td>")
document.write("<td style=\"\">3★</td>")
document.write("<td style=\"\">4★</td>")
document.write("<td style=\"\">5★</td>")
document.write("<td style=\"\"></td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_3\">		<td style=\"\">活力軟糖</td>")
document.write("<td style=\"\">回復</td>")
document.write("<td style=\"\">HP回復</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">40</td>")
document.write("<td style=\"\">60</td>")
document.write("<td style=\"\">80</td>")
document.write("<td style=\"\">100</td>")
document.write("<td style=\"\">120</td>")
document.write("<td style=\"\">8</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_4\">		<td style=\"\">魔力軟糖</td>")
document.write("<td style=\"\">回復</td>")
document.write("<td style=\"\">MP回復</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">25</td>")
document.write("<td style=\"\">37</td>")
document.write("<td style=\"\">50</td>")
document.write("<td style=\"\">62</td>")
document.write("<td style=\"\">75</td>")
document.write("<td style=\"\">8</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_5\">		<td style=\"\">生命瓶</td>")
document.write("<td style=\"\">回復</td>")
document.write("<td style=\"\">HP回復</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">50</td>")
document.write("<td style=\"\">97</td>")
document.write("<td style=\"\">145</td>")
document.write("<td style=\"\">192</td>")
document.write("<td style=\"\">240</td>")
document.write("<td style=\"\">10</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_6\">		<td style=\"\">恩惠的生命之符</td>")
document.write("<td style=\"\">回復</td>")
document.write("<td style=\"\">MP槽修復<br>MP回復</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">99<br>40</td>")
document.write("<td style=\"\">148<br>60</td>")
document.write("<td style=\"\">198<br>80</td>")
document.write("<td style=\"\">247<br>100</td>")
document.write("<td style=\"\">297<br>120</td>")
document.write("<td style=\"\">5</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_7\">		<td style=\"\">禁忌的蘋果</td>")
document.write("<td style=\"\">？？？</td>")
document.write("<td style=\"\">興奮值上升<br>附加催淫</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">99</td>")
document.write("<td style=\"\">149</td>")
document.write("<td style=\"\">199</td>")
document.write("<td style=\"\">249</td>")
document.write("<td style=\"\">299</td>")
document.write("<td style=\"\">8</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_8\">		<td style=\"\">血櫻桃 </td>")
document.write("<td style=\"\">果實</td>")
document.write("<td style=\"\">最大HP上昇&amp;諾艾爾的HP回復</td>")
document.write("<td style=\"\">+10%</td>")
document.write("<td style=\"\">+12%</td>")
document.write("<td style=\"\">+14%</td>")
document.write("<td style=\"\">+16%</td>")
document.write("<td style=\"\">+18%</td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\">8</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_9\">		<td style=\"\">血蘋果</td>")
document.write("<td style=\"\">果實</td>")
document.write("<td style=\"\">最大HP上昇&amp;諾艾爾的HP回復</td>")
document.write("<td style=\"\">+30%</td>")
document.write("<td style=\"\">+34%</td>")
document.write("<td style=\"\">+37％</td>")
document.write("<td style=\"\">+41%</td>")
document.write("<td style=\"\">+45%</td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\">8</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_10\">		<td style=\"\">血鳳梨</td>")
document.write("<td style=\"\">果實</td>")
document.write("<td style=\"\">最大HP上昇&amp;諾艾爾的HP回復</td>")
document.write("<td style=\"\">+60%</td>")
document.write("<td style=\"\">+65%</td>")
document.write("<td style=\"\">+70％</td>")
document.write("<td style=\"\">+75%</td>")
document.write("<td style=\"\">+81%</td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\">8</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_11\">		<td style=\"\">黑暗精髓</td>")
document.write("<td style=\"\">水</td>")
document.write("<td style=\"\">被拘束時的MP傷害</td>")
document.write("<td style=\"\">-12%</td>")
document.write("<td style=\"\">-19%</td>")
document.write("<td style=\"\">-25%</td>")
document.write("<td style=\"\">-31%</td>")
document.write("<td style=\"\">38%</td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\">8</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_12\">		<td style=\"\">凝膠</td>")
document.write("<td style=\"\">肉</td>")
document.write("<td style=\"\">物理攻撃力、散彈槍威力</td>")
document.write("<td style=\"\">+4%</td>")
document.write("<td style=\"\">+6％</td>")
document.write("<td style=\"\">+8%</td>")
document.write("<td style=\"\">+10%</td>")
document.write("<td style=\"\">+12%</td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_13\">		<td style=\"\">新鲜的水</td>")
document.write("<td style=\"\">水</td>")
document.write("<td style=\"\">詠唱中受傷時的魔力喪失量</td>")
document.write("<td style=\"\">-6%</td>")
document.write("<td style=\"\">-10%</td>")
document.write("<td style=\"\">-13％</td>")
document.write("<td style=\"\">-16%</td>")
document.write("<td style=\"\">-20%</td>")
document.write("<td style=\"\">7</td>")
document.write("<td style=\"\">10</td>")
document.write("<td style=\"\">14</td>")
document.write("<td style=\"\">17</td>")
document.write("<td style=\"\">21</td>")
document.write("<td style=\"\">10</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_14\">		<td style=\"\">諾艾爾果汁</td>")
document.write("<td style=\"\">水</td>")
document.write("<td style=\"\">最大MP上昇<br><span style=\"color: #F54738;\">状態異常持續時間</span><br><span style=\"color: #F54738;\">狀態異常耐性</span></td>")
document.write("<td style=\"\">+6%<br><span style=\"color: #F54738;\">+19%</span><br><span style=\"color: #F54738;\">-12%</span></td>")
document.write("<td style=\"\">+10%<br><span style=\"color: #F54738;\">+32%</span><br><span style=\"color: #F54738;\">-18%</span></td>")
document.write("<td style=\"\">+13%<br><span style=\"color: #F54738;\">+49%</span><br><span style=\"color: #F54738;\">-25%</span></td>")
document.write("<td style=\"\">+16%<br><span style=\"color: #F54738;\">+69%</span><br><span style=\"color: #F54738;\">-31%</span></td>")
document.write("<td style=\"\">+20%<br><span style=\"color: #F54738;\">+96%</span><br><span style=\"color: #F54738;\">-37%</span></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\">5</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_15\">		<td style=\"\">小麥</td>")
document.write("<td style=\"\">穀物</td>")
document.write("<td style=\"\">魔術使用後所飛散的魔力 敵人更不容易回收</td>")
document.write("<td style=\"\">+29%</td>")
document.write("<td style=\"\">+44%</td>")
document.write("<td style=\"\">+58%</td>")
document.write("<td style=\"\">+73%</td>")
document.write("<td style=\"\">+88%</td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_16\">		<td style=\"\">萵苣</td>")
document.write("<td style=\"\">蔬菜</td>")
document.write("<td style=\"\">護盾強化</td>")
document.write("<td style=\"\">+18%</td>")
document.write("<td style=\"\">+28%</td>")
document.write("<td style=\"\">+37%</td>")
document.write("<td style=\"\">+46%</td>")
document.write("<td style=\"\">+56%</td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_17\">		<td style=\"\">魔族的肝</td>")
document.write("<td style=\"\">其他</td>")
document.write("<td style=\"\">最大MP上昇</td>")
document.write("<td style=\"\">+6%</td>")
document.write("<td style=\"\">+10%</td>")
document.write("<td style=\"\">+13%</td>")
document.write("<td style=\"\">+16％</td>")
document.write("<td style=\"\">+20%</td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_18\">		<td style=\"\">魔族的肉</td>")
document.write("<td style=\"\">肉</td>")
document.write("<td style=\"\">物理攻撃力、散彈槍威力<br>魔法攻撃力、散彈槍威力</td>")
document.write("<td style=\"\">+4%<br>+6%</td>")
document.write("<td style=\"\">+7%<br>+9%</td>")
document.write("<td style=\"\">+9%<br>+12%</td>")
document.write("<td style=\"\">+11％<br>+15％</td>")
document.write("<td style=\"\">+14%<br>+18％</td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\">8</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_19\">		<td style=\"\">家畜的肉</td>")
document.write("<td style=\"\">肉</td>")
document.write("<td style=\"\">物理攻撃力、散彈槍威力</td>")
document.write("<td style=\"\">+12%</td>")
document.write("<td style=\"\">+19%</td>")
document.write("<td style=\"\">+25%</td>")
document.write("<td style=\"\">+31％</td>")
document.write("<td style=\"\">+38％</td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\">8</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_20\">		<td style=\"\">高麗菜</td>")
document.write("<td style=\"\">蔬菜</td>")
document.write("<td style=\"\">被拘束時的HP傷害</td>")
document.write("<td style=\"\">-17%</td>")
document.write("<td style=\"\">-26％</td>")
document.write("<td style=\"\">-34%</td>")
document.write("<td style=\"\">-44%</td>")
document.write("<td style=\"\">-52%</td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_21\">		<td style=\"\">番茄</td>")
document.write("<td style=\"\">蔬菜</td>")
document.write("<td style=\"\">回避、受身的無敵時間増大</td>")
document.write("<td style=\"\">+18%</td>")
document.write("<td style=\"\">+28%</td>")
document.write("<td style=\"\">+37%</td>")
document.write("<td style=\"\">+46%</td>")
document.write("<td style=\"\">+56%</td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_22\">		<td style=\"\">青椒</td>")
document.write("<td style=\"\">蔬菜</td>")
document.write("<td style=\"\">有毒瓦斯傷害</td>")
document.write("<td style=\"\">-21%</td>")
document.write("<td style=\"\">-32％</td>")
document.write("<td style=\"\">-41%</td>")
document.write("<td style=\"\">-52%</td>")
document.write("<td style=\"\">-63%</td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_23\">		<td style=\"\">甜椒</td>")
document.write("<td style=\"\">蔬菜</td>")
document.write("<td style=\"\">逃脫容易度</td>")
document.write("<td style=\"\">+23%</td>")
document.write("<td style=\"\">+35％</td>")
document.write("<td style=\"\">+46%</td>")
document.write("<td style=\"\">+58%</td>")
document.write("<td style=\"\">+70%</td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_24\">		<td style=\"\">芹菜</td>")
document.write("<td style=\"\">蔬菜</td>")
document.write("<td style=\"\">電撃傷害</td>")
document.write("<td style=\"\">-17%</td>")
document.write("<td style=\"\">-26%</td>")
document.write("<td style=\"\">-34％</td>")
document.write("<td style=\"\">-44%</td>")
document.write("<td style=\"\">-52%</td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_25\">		<td style=\"\">牛蒡</td>")
document.write("<td style=\"\">蔬菜</td>")
document.write("<td style=\"\">詠唱中受傷時的魔力喪失量</td>")
document.write("<td style=\"\">-23%</td>")
document.write("<td style=\"\">-35%</td>")
document.write("<td style=\"\">-46％</td>")
document.write("<td style=\"\">-58%</td>")
document.write("<td style=\"\">-70%</td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_26\">		<td style=\"\">甜菜</td>")
document.write("<td style=\"\">蔬菜、調味料</td>")
document.write("<td style=\"\">料理全體効果</td>")
document.write("<td style=\"\">+3%</td>")
document.write("<td style=\"\">+4%</td>")
document.write("<td style=\"\">+6%</td>")
document.write("<td style=\"\">+7%</td>")
document.write("<td style=\"\">+9%</td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_27\">		<td style=\"\">黃瓜</td>")
document.write("<td style=\"\">蔬菜</td>")
document.write("<td style=\"\">被拘束時的MP傷害</td>")
document.write("<td style=\"\">-12%</td>")
document.write("<td style=\"\">-19%</td>")
document.write("<td style=\"\">-25%</td>")
document.write("<td style=\"\">-31％</td>")
document.write("<td style=\"\">-38%</td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_28\">		<td style=\"\">大頭菜</td>")
document.write("<td style=\"\">蔬菜</td>")
document.write("<td style=\"\">MP乾枯時的詠唱速度</td>")
document.write("<td style=\"\">+23%</td>")
document.write("<td style=\"\">+35%</td>")
document.write("<td style=\"\">+46%</td>")
document.write("<td style=\"\">+58%</td>")
document.write("<td style=\"\">+70%</td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_29\">		<td style=\"\">玉米</td>")
document.write("<td style=\"\">穀物、蔬菜</td>")
document.write("<td style=\"\">寶箱轉盤的速度</td>")
document.write("<td style=\"\">-14%</td>")
document.write("<td style=\"\">-22％</td>")
document.write("<td style=\"\">-29%</td>")
document.write("<td style=\"\">-36%</td>")
document.write("<td style=\"\">-44%</td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_30\">		<td style=\"\">洋蔥</td>")
document.write("<td style=\"\">蔬菜</td>")
document.write("<td style=\"\">狀態異常耐性</td>")
document.write("<td style=\"\">+10%</td>")
document.write("<td style=\"\">+15%</td>")
document.write("<td style=\"\">+20%</td>")
document.write("<td style=\"\">+25%</td>")
document.write("<td style=\"\">+30%</td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_31\">		<td style=\"\">茄子</td>")
document.write("<td style=\"\">蔬菜</td>")
document.write("<td style=\"\">火焰傷害</td>")
document.write("<td style=\"\">-17％</td>")
document.write("<td style=\"\">-26%</td>")
document.write("<td style=\"\">-34%</td>")
document.write("<td style=\"\">-44%</td>")
document.write("<td style=\"\">-52%</td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_32\">		<td style=\"\">蒜頭</td>")
document.write("<td style=\"\">調味料</td>")
document.write("<td style=\"\">詠唱中受傷時的魔力喪失量</td>")
document.write("<td style=\"\">-6%</td>")
document.write("<td style=\"\">-10%</td>")
document.write("<td style=\"\">-13%</td>")
document.write("<td style=\"\">-16%</td>")
document.write("<td style=\"\">-20%</td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_33\">		<td style=\"\">青花菜</td>")
document.write("<td style=\"\">蔬菜</td>")
document.write("<td style=\"\">MP槽不容易破裂</td>")
document.write("<td style=\"\">+23%</td>")
document.write("<td style=\"\">+35％</td>")
document.write("<td style=\"\">+46%</td>")
document.write("<td style=\"\">+58%</td>")
document.write("<td style=\"\">+70%</td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_34\">		<td style=\"\">諾艾爾蛋</td>")
document.write("<td style=\"\">卵</td>")
document.write("<td style=\"\">詠唱速度<br><span style=\"color: #F54738;\">容易逃脫度</span>-</td>")
document.write("<td style=\"\">+20%<br><span style=\"color: #F54738;\">-16%</span></td>")
document.write("<td style=\"\">+30%<br><span style=\"color: #F54738;\">-24%</span></td>")
document.write("<td style=\"\">+40%<br><span style=\"color: #F54738;\">-33%</span></td>")
document.write("<td style=\"\">+50%<br><span style=\"color: #F54738;\">-41%</span></td>")
document.write("<td style=\"\">+60%<br><span style=\"color: #F54738;\">-49%</span></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_35\">		<td style=\"\">家畜的卵</td>")
document.write("<td style=\"\">卵</td>")
document.write("<td style=\"\">詠唱速度+</td>")
document.write("<td style=\"\">+15%</td>")
document.write("<td style=\"\">+22%</td>")
document.write("<td style=\"\">+30%</td>")
document.write("<td style=\"\">+37%</td>")
document.write("<td style=\"\">+45%</td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_36\">		<td style=\"\">野蘑菇</td>")
document.write("<td style=\"\">蘑菇</td>")
document.write("<td style=\"\">隨機的効果</td>")
document.write("<td style=\"\">+33%</td>")
document.write("<td style=\"\">+49%</td>")
document.write("<td style=\"\">+66%</td>")
document.write("<td style=\"\">+82%</td>")
document.write("<td style=\"\">+99%</td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_37\">		<td style=\"\">斑點蘑菇</td>")
document.write("<td style=\"\">蘑菇</td>")
document.write("<td style=\"\">隨機的効果<br><span style=\"color: #F54738;\">狀態異常耐性</span><br><span style=\"color: #F54738;\">被拘束容易逃脫度</span><br><span style=\"color: #F54738;\">有毒瓦斯傷害</span></td>")
document.write("<td style=\"\">+46%<br><span style=\"color: #F54738;\">-12%</span><br><span style=\"color: #F54738;\">-9%</span><br><span style=\"color: #F54738;\">+8%</span></td>")
document.write("<td style=\"\">+70%<br><span style=\"color: #F54738;\">-18%</span><br><span style=\"color: #F54738;\">-14%</span><br><span style=\"color: #F54738;\">+13%</span></td>")
document.write("<td style=\"\">+93%<br><span style=\"color: #F54738;\">-25%</span><br><span style=\"color: #F54738;\">-19%</span><br><span style=\"color: #F54738;\">+17%</span></td>")
document.write("<td style=\"\">+116%<br><span style=\"color: #F54738;\">-31%</span><br><span style=\"color: #F54738;\">-24%</span><br><span style=\"color: #F54738;\">+22%</span></td>")
document.write("<td style=\"\">+140%<br><span style=\"color: #F54738;\">-37%</span><br><span style=\"color: #F54738;\">-29%</span><br><span style=\"color: #F54738;\">+26%</span></td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">5</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_38\">		<td style=\"\">岩鹽</td>")
document.write("<td style=\"\">調味料</td>")
document.write("<td style=\"\">料理全体効果</td>")
document.write("<td style=\"\">+6%</td>")
document.write("<td style=\"\">+10%</td>")
document.write("<td style=\"\">+13%</td>")
document.write("<td style=\"\">+16%</td>")
document.write("<td style=\"\">+20%</td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\"></td>")
document.write("<td style=\"\">10</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_39\">		<td style=\"\">辛香料小瓶</td>")
document.write("<td style=\"\">調味料</td>")
document.write("<td style=\"\">料理全体の効果</td>")
document.write("<td style=\"\">-</td>")
document.write("<td style=\"\">-</td>")
document.write("<td style=\"\">-</td>")
document.write("<td style=\"\">+20%</td>")
document.write("<td style=\"\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">10</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_40\">		<td style=\"\">胡椒</td>")
document.write("<td style=\"\">調味料</td>")
document.write("<td style=\"\">容易逃脫度</td>")
document.write("<td style=\"\">+13％</td>")
document.write("<td style=\"\">+20%</td>")
document.write("<td style=\"\">+26%</td>")
document.write("<td style=\"\">+33%</td>")
document.write("<td style=\"\">+44%</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_41\">		<td style=\"\">紅蘿蔔</td>")
document.write("<td style=\"\">蔬菜</td>")
document.write("<td style=\"\">容易跌倒</td>")
document.write("<td style=\"\">-23％</td>")
document.write("<td style=\"\">-35%</td>")
document.write("<td style=\"\">-46%</td>")
document.write("<td style=\"\">-58%</td>")
document.write("<td style=\"\">-70%</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_42\">		<td style=\"\">毒的種子</td>")
document.write("<td style=\"\">其他</td>")
document.write("<td style=\"\">狀態異常耐性</td>")
document.write("<td style=\"\">+4%</td>")
document.write("<td style=\"\">+5％</td>")
document.write("<td style=\"\">+8%</td>")
document.write("<td style=\"\">+9%</td>")
document.write("<td style=\"\">+11%</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_43\">		<td style=\"\">枯草</td>")
document.write("<td style=\"\">蔬菜</td>")
document.write("<td style=\"text-align:center;\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_44\">		<td style=\"\">魔族的皮膚</td>")
document.write("<td style=\"\">其他</td>")
document.write("<td style=\"text-align:center;\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_45\">		<td style=\"\">玻璃碎片</td>")
document.write("<td style=\"\">其他</td>")
document.write("<td style=\"text-align:center;\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_46\">		<td style=\"\">迷迭香</td>")
document.write("<td style=\"\">藥草</td>")
document.write("<td style=\"\">MP槽不容易破裂</td>")
document.write("<td style=\"\">+13%</td>")
document.write("<td style=\"\">+20%</td>")
document.write("<td style=\"\">+26%</td>")
document.write("<td style=\"\">+33%</td>")
document.write("<td style=\"\">+40%</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_47\">		<td style=\"\">羅勒</td>")
document.write("<td style=\"\">藥草</td>")
document.write("<td style=\"\">狀態異常耐性</td>")
document.write("<td style=\"\">+11%</td>")
document.write("<td style=\"\">+16%</td>")
document.write("<td style=\"\">+22%</td>")
document.write("<td style=\"\">+28%</td>")
document.write("<td style=\"\">+34%</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_48\">		<td style=\"\">檸檬草</td>")
document.write("<td style=\"\">藥草</td>")
document.write("<td style=\"\">被拘束時的MP傷害</td>")
document.write("<td style=\"\">-10％</td>")
document.write("<td style=\"\">-16％</td>")
document.write("<td style=\"\">-22％</td>")
document.write("<td style=\"\">-27％</td>")
document.write("<td style=\"\">-33％</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_49\">		<td style=\"\">鼠尾草</td>")
document.write("<td style=\"\">藥草</td>")
document.write("<td style=\"\">状態異常持續時間</td>")
document.write("<td style=\"\">-12％</td>")
document.write("<td style=\"\">-17％</td>")
document.write("<td style=\"\">-21％</td>")
document.write("<td style=\"\">-25％</td>")
document.write("<td style=\"\">-29％</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_50\">		<td style=\"\">香葉天竺葵</td>")
document.write("<td style=\"\">藥草</td>")
document.write("<td style=\"\"><span style=\"color: #F54738;\">詠唱中受傷時的魔力喪失量</span><br>有毒瓦斯傷害</td>")
document.write("<td style=\"\"><span style=\"color: #F54738;\">+9%</span><br>-18％</td>")
document.write("<td style=\"\"><span style=\"color: #F54738;\">+14%</span><br>-27％</td>")
document.write("<td style=\"\"><span style=\"color: #F54738;\">+19%</span><br>-36％</td>")
document.write("<td style=\"\"><span style=\"color: #F54738;\">+24%</span><br>-45％</td>")
document.write("<td style=\"\"><span style=\"color: #F54738;\">+29%</span><br>-54％</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_51\">		<td style=\"\">辣薄荷</td>")
document.write("<td style=\"\">藥草</td>")
document.write("<td style=\"\"><span style=\"color: #F54738;\">容易跌倒</span><br>弱攻撃奪取的魔力量増加</td>")
document.write("<td style=\"\"><span style=\"color: #F54738;\">+19％</span><br>+20％</td>")
document.write("<td style=\"\"><span style=\"color: #F54738;\">+29％</span><br>+30％</td>")
document.write("<td style=\"\"><span style=\"color: #F54738;\">+39％</span><br>+40％</td>")
document.write("<td style=\"\"><span style=\"color: #F54738;\">+49％</span><br>+50％</td>")
document.write("<td style=\"\"><span style=\"color: #F54738;\">+59%</span><br>+60％</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_52\">		<td style=\"\">木天蓼</td>")
document.write("<td style=\"\">藥草</td>")
document.write("<td style=\"\">MP乾枯時的詠唱速度<br><span style=\"color: #F54738;\">逃脫容易度</span></td>")
document.write("<td style=\"\">+20%<br><span style=\"color: #F54738;\">-11%</span></td>")
document.write("<td style=\"\">+30%<br><span style=\"color: #F54738;\">-17%</span></td>")
document.write("<td style=\"\">+40%<br><span style=\"color: #F54738;\">-23%</span></td>")
document.write("<td style=\"\">+50%<br><span style=\"color: #F54738;\">-29%</span></td>")
document.write("<td style=\"\">+60%<br><span style=\"color: #F54738;\">-34%</span></td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_53\">		<td style=\"\">洋甘菊</td>")
document.write("<td style=\"\">藥草</td>")
document.write("<td style=\"\">火焰傷害<br>電撃傷害<br>冰凍傷害</td>")
document.write("<td style=\"\">-6％<br>-6％<br>-6％</td>")
document.write("<td style=\"\">-9％<br>-9％<br>-9％</td>")
document.write("<td style=\"\">-12％<br>-12％<br>-12％</td>")
document.write("<td style=\"\">-15％<br>-15％<br>-15％</td>")
document.write("<td style=\"\">-19％<br>-19％<br>-19％</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_54\">		<td style=\"\">石炭</td>")
document.write("<td style=\"\">其他</td>")
document.write("<td style=\"text-align:center;\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">30</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_55\">		<td style=\"\">水晶</td>")
document.write("<td style=\"\">其他</td>")
document.write("<td style=\"text-align:center;\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">20</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_56\">		<td style=\"\">紫水晶</td>")
document.write("<td style=\"\">其他</td>")
document.write("<td style=\"text-align:center;\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">10</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_57\">		<td style=\"\">鐵</td>")
document.write("<td style=\"\">其他</td>")
document.write("<td style=\"text-align:center;\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">10</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_58\">		<td style=\"\">鉻</td>")
document.write("<td style=\"\">其他</td>")
document.write("<td style=\"text-align:center;\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">10</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_59\">		<td style=\"\">硫磺</td>")
document.write("<td style=\"\">其他</td>")
document.write("<td style=\"text-align:center;\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">10</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_60\">		<td style=\"\">硝石</td>")
document.write("<td style=\"\">其他</td>")
document.write("<td style=\"text-align:center;\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">10</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_61\">		<td style=\"\">金礦石</td>")
document.write("<td style=\"\">其他</td>")
document.write("<td style=\"text-align:center;\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">10</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_62\">		<td style=\"\">紅色綠柱石</td>")
document.write("<td style=\"\">其他</td>")
document.write("<td style=\"text-align:center;\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">10</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_63\">		<td style=\"\">藍寶石</td>")
document.write("<td style=\"\">其他</td>")
document.write("<td style=\"text-align:center;\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">10</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_64\">		<td style=\"\">黃玉</td>")
document.write("<td style=\"\">其他</td>")
document.write("<td style=\"text-align:center;\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">10</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_65\">		<td style=\"\">摩根石</td>")
document.write("<td style=\"\">其他</td>")
document.write("<td style=\"text-align:center;\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">10</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_66\">		<td style=\"\">貓石</td>")
document.write("<td style=\"\">其他</td>")
document.write("<td style=\"text-align:center;\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">10</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_67\">		<td style=\"\">木材</td>")
document.write("<td style=\"\">其他</td>")
document.write("<td style=\"text-align:center;\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">30</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_68\">		<td style=\"\">石頭</td>")
document.write("<td style=\"\">其他</td>")
document.write("<td style=\"text-align:center;\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">30</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_69\">		<td style=\"\">史萊姆的假蛋</td>")
document.write("<td style=\"\">其他</td>")
document.write("<td style=\"text-align:center;\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">5</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_70\">		<td style=\"\">黑色棉花胞子</td>")
document.write("<td style=\"\">其他</td>")
document.write("<td style=\"text-align:center;\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">5</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_71\">		<td style=\"\">木偶的右手</td>")
document.write("<td style=\"\">其他</td>")
document.write("<td style=\"text-align:center;\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">5</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_72\">		<td style=\"\">劍山荊棘</td>")
document.write("<td style=\"\">其他</td>")
document.write("<td style=\"text-align:center;\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">5</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_73\">		<td style=\"\">蛇皮</td>")
document.write("<td style=\"\">其他</td>")
document.write("<td style=\"text-align:center;\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">5</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_74\">		<td style=\"\">跳動的蜥蜴尾巴</td>")
document.write("<td style=\"\">其他</td>")
document.write("<td style=\"text-align:center;\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">5</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_75\">		<td style=\"\">海綿的圓殼</td>")
document.write("<td style=\"\">其他</td>")
document.write("<td style=\"text-align:center;\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">5</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_76\">		<td style=\"\">空瓶子</td>")
document.write("<td style=\"\">其他</td>")
document.write("<td style=\"text-align:center;\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">1</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_77\">		<td style=\"\">便當盒</td>")
document.write("<td style=\"\">其他</td>")
document.write("<td style=\"text-align:center;\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">1</td></tr>")
document.write(" <tr class=\"atwiki_tr_even atwiki_tr_78\">		<td style=\"\">商人的鈴</td>")
document.write("<td style=\"\">其他</td>")
document.write("<td style=\"text-align:center;\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">1</td></tr>")
document.write(" <tr class=\"atwiki_tr_odd atwiki_tr_79\">		<td style=\"\">背包擴充配件</td>")
document.write("<td style=\"\">強化</td>")
document.write("<td style=\"\">擴大背包能取得的物品就會增加。。</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"text-align:center;\" colspan=\"5\">-</td>")
document.write("<td style=\"\">-</td></tr>")
document.write(" </tbody></table>")
document.write("")
