document.writeIn("<table>")
document.writeIn("    <tbody><tr class="atwiki_tr_odd atwiki_tr_1">		<td rowspan="2" style="background-color:#CFC;vertical-align:MIDDLE;">Item Name</td>")
document.writeIn("            <td rowspan="2" style="background-color:#CFC;vertical-align:MIDDLE;">Category</td>")
document.writeIn("            <td rowspan="2" style="background-color:#CFC;vertical-align:MIDDLE;">Ingredient Effect &amp; Item Function</td>")
document.writeIn("            <td style="background-color:#CFC;text-align:center;" colspan="5">Food Effect</td>")
document.writeIn("            <td style="background-color:#CFC;text-align:center;" colspan="5">Item Effect</td>")
document.writeIn("            <td style="background-color:#CFC;text-align:center;">Max Stacking Count</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_2">")
document.writeIn("            <td style="">1★</td>")
document.writeIn("            <td style="">2★</td>")
document.writeIn("            <td style="">3★</td>")
document.writeIn("            <td style="">4★</td>")
document.writeIn("            <td style="">5★</td>")
document.writeIn("            <td style="">1★</td>")
document.writeIn("            <td style="">2★</td>")
document.writeIn("            <td style="">3★</td>")
document.writeIn("            <td style="">4★</td>")
document.writeIn("            <td style="">5★</td>")
document.writeIn("            <td style=""></td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_3">		<td style="">Vital Gummy</td>")
document.writeIn("            <td style=""> Recovery</td>")
document.writeIn("            <td style="">HP Recovery</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">40</td>")
document.writeIn("            <td style="">60</td>")
document.writeIn("            <td style="">80</td>")
document.writeIn("            <td style="">100</td>")
document.writeIn("            <td style="">120</td>")
document.writeIn("            <td style="">8</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_4">		<td style="">Magical Gummy</td>")
document.writeIn("            <td style=""> Recovery</td>")
document.writeIn("            <td style="">MP Recovery</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">25</td>")
document.writeIn("            <td style="">37</td>")
document.writeIn("            <td style="">50</td>")
document.writeIn("            <td style="">62</td>")
document.writeIn("            <td style="">75</td>")
document.writeIn("            <td style="">8</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_5">		<td style="">Life Bottle</td>")
document.writeIn("            <td style=""> Recovery</td>")
document.writeIn("            <td style="">HP Recovery</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">50</td>")
document.writeIn("            <td style="">97</td>")
document.writeIn("            <td style="">145</td>")
document.writeIn("            <td style="">192</td>")
document.writeIn("            <td style="">240</td>")
document.writeIn("            <td style="">10</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_6">		<td style="">Ankh of Gracia</td>")
document.writeIn("            <td style=""> Recovery</td>")
document.writeIn("            <td style="">Restore MP Gauge<br>MP Recovery</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">99<br>40</td>")
document.writeIn("            <td style="">148<br>60</td>")
document.writeIn("            <td style="">198<br>80</td>")
document.writeIn("            <td style="">247<br>100</td>")
document.writeIn("            <td style="">297<br>120</td>")
document.writeIn("            <td style="">5</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_7">		<td style="">Purple Malus</td>")
document.writeIn("            <td style="">？？？</td>")
document.writeIn("            <td style="">Increase AR Point<br>Give sexual arousal</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">99</td>")
document.writeIn("            <td style="">149</td>")
document.writeIn("            <td style="">199</td>")
document.writeIn("            <td style="">249</td>")
document.writeIn("            <td style="">299</td>")
document.writeIn("            <td style="">8</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_8">		<td style="">Blood Cherry </td>")
document.writeIn("            <td style="">Fruit</td>")
document.writeIn("            <td style="">Increase Max HP &amp; Recovers Noel's Health</td>")
document.writeIn("            <td style="">+10%</td>")
document.writeIn("            <td style="">+12%</td>")
document.writeIn("            <td style="">+14%</td>")
document.writeIn("            <td style="">+16%</td>")
document.writeIn("            <td style="">+18%</td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style="">8</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_9">		<td style="">Blood Apple</td>")
document.writeIn("            <td style="">Fruit</td>")
document.writeIn("            <td style="">Increase Max HP &amp; Recovers Noel's Health</td>")
document.writeIn("            <td style="">+30%</td>")
document.writeIn("            <td style="">+34%</td>")
document.writeIn("            <td style="">+37％</td>")
document.writeIn("            <td style="">+41%</td>")
document.writeIn("            <td style="">+45%</td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style="">8</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_10">		<td style="">Blood Pine</td>")
document.writeIn("            <td style="">Fruit</td>")
document.writeIn("            <td style="">Increase Max HP &amp; Recovers Noel's Health</td>")
document.writeIn("            <td style="">+60%</td>")
document.writeIn("            <td style="">+65%</td>")
document.writeIn("            <td style="">+70％</td>")
document.writeIn("            <td style="">+75%</td>")
document.writeIn("            <td style="">+81%</td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style="">8</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_11">		<td style="">Dark Essence</td>")
document.writeIn("            <td style="">Water</td>")
document.writeIn("            <td style="">Reduce MP Damage when restrained</td>")
document.writeIn("            <td style="">-12%</td>")
document.writeIn("            <td style="">-19%</td>")
document.writeIn("            <td style="">-25%</td>")
document.writeIn("            <td style="">-31%</td>")
document.writeIn("            <td style="">-38%</td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style="">8</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_12">		<td style="">Gel</td>")
document.writeIn("            <td style="">Meat</td>")
document.writeIn("            <td style="">Increase Physical Attack、Increase Shotgun Damage</td>")
document.writeIn("            <td style="">+4%</td>")
document.writeIn("            <td style="">+6％</td>")
document.writeIn("            <td style="">+8%</td>")
document.writeIn("            <td style="">+10%</td>")
document.writeIn("            <td style="">+12%</td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_13">		<td style="">Fresh Water</td>")
document.writeIn("            <td style="">Water</td>")
document.writeIn("            <td style="">Calms down &amp; Reduce Mana lost when chanting</td>")
document.writeIn("            <td style="">-6%</td>")
document.writeIn("            <td style="">-10%</td>")
document.writeIn("            <td style="">-13％</td>")
document.writeIn("            <td style="">-16%</td>")
document.writeIn("            <td style="">-20%</td>")
document.writeIn("            <td style="">7</td>")
document.writeIn("            <td style="">10</td>")
document.writeIn("            <td style="">14</td>")
document.writeIn("            <td style="">17</td>")
document.writeIn("            <td style="">21</td>")
document.writeIn("            <td style="">10</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_14">		<td style="">Noel Juice</td>")
document.writeIn("            <td style="">Water</td>")
document.writeIn("            <td style="">Increase Maximum MP<br><span style="color: #F54738;">time of abnormal effects</span><br><span style="color: #F54738;">Resist abnormal effects</span></td>")
document.writeIn("            <td style="">+6%<br><span style="color: #F54738;">+19%</span><br><span style="color: #F54738;">-12%</span></td>")
document.writeIn("            <td style="">+10%<br><span style="color: #F54738;">+32%</span><br><span style="color: #F54738;">-18%</span></td>")
document.writeIn("            <td style="">+13%<br><span style="color: #F54738;">+49%</span><br><span style="color: #F54738;">-25%</span></td>")
document.writeIn("            <td style="">+16%<br><span style="color: #F54738;">+69%</span><br><span style="color: #F54738;">-31%</span></td>")
document.writeIn("            <td style="">+20%<br><span style="color: #F54738;">+96%</span><br><span style="color: #F54738;">-37%</span></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style="">5</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_15">		<td style="">Wheat </td>")
document.writeIn("            <td style="">Grain </td>")
document.writeIn("            <td style="">Enemies will absord less mana from magic attacks <br></td>")
document.writeIn("            <td style="">+29%</td>")
document.writeIn("            <td style="">+44%</td>")
document.writeIn("            <td style="">+58%</td>")
document.writeIn("            <td style="">+73%</td>")
document.writeIn("            <td style="">+88%</td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_16">		<td style="">Lettuce </td>")
document.writeIn("            <td style="">Vegetable </td>")
document.writeIn("            <td style="">Shield Strength</td>")
document.writeIn("            <td style="">+18%</td>")
document.writeIn("            <td style="">+28%</td>")
document.writeIn("            <td style="">+37%</td>")
document.writeIn("            <td style="">+46%</td>")
document.writeIn("            <td style="">+56%</td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_17">		<td style="">Monster's Liver </td>")
document.writeIn("            <td style="">Other </td>")
document.writeIn("            <td style="">Increase Max MP </td>")
document.writeIn("            <td style="">+6%</td>")
document.writeIn("            <td style="">+10%</td>")
document.writeIn("            <td style="">+13%</td>")
document.writeIn("            <td style="">+16％</td>")
document.writeIn("            <td style="">+20%</td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_18">		<td style="">Monster's Meat </td>")
document.writeIn("            <td style="">Meat </td>")
document.writeIn("            <td style="">Increase Physical Attack、 Increase Shotgun Damage <br>Increase Magic Damager、 Increase Shotgun Damage</td>")
document.writeIn("            <td style="">+4%<br>+6%</td>")
document.writeIn("            <td style="">+7%<br>+9%</td>")
document.writeIn("            <td style="">+9%<br>+12%</td>")
document.writeIn("            <td style="">+11％<br>+15％</td>")
document.writeIn("            <td style="">+14%<br>+18％</td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style="">8</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_19">		<td style="">Livestock Meat </td>")
document.writeIn("            <td style="">Meat </td>")
document.writeIn("            <td style="">Increase Physical Attack 、Increase Shotgun Damage</td>")
document.writeIn("            <td style="">+12%</td>")
document.writeIn("            <td style="">+19%</td>")
document.writeIn("            <td style="">+25%</td>")
document.writeIn("            <td style="">+31％</td>")
document.writeIn("            <td style="">+38％</td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style="">8</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_20">		<td style="">Cabbage </td>")
document.writeIn("            <td style="">Vegetable </td>")
document.writeIn("            <td style="">Reduce HP damage when restrained</td>")
document.writeIn("            <td style="">-17%</td>")
document.writeIn("            <td style="">-26％</td>")
document.writeIn("            <td style="">-34%</td>")
document.writeIn("            <td style="">-44%</td>")
document.writeIn("            <td style="">-52%</td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_21">		<td style="">Tomato </td>")
document.writeIn("            <td style="">Vegetable </td>")
document.writeIn("            <td style="">Increase invincibility time when evading or getting back up</td>")
document.writeIn("            <td style="">+18%</td>")
document.writeIn("            <td style="">+28%</td>")
document.writeIn("            <td style="">+37%</td>")
document.writeIn("            <td style="">+46%</td>")
document.writeIn("            <td style="">+56%</td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_22">		<td style="">Green Pepper </td>")
document.writeIn("            <td style="">Vegetable </td>")
document.writeIn("            <td style="">Easier to escape when restrained</td>")
document.writeIn("            <td style="">-21%</td>")
document.writeIn("            <td style="">-32％</td>")
document.writeIn("            <td style="">-41%</td>")
document.writeIn("            <td style="">-52%</td>")
document.writeIn("            <td style="">-63%</td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_23">		<td style="">Bell Pepper </td>")
document.writeIn("            <td style="">Vegetable </td>")
document.writeIn("            <td style="">Resist smoke</td>")
document.writeIn("            <td style="">+23%</td>")
document.writeIn("            <td style="">+35％</td>")
document.writeIn("            <td style="">+46%</td>")
document.writeIn("            <td style="">+58%</td>")
document.writeIn("            <td style="">+70%</td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_24">		<td style="">Celery </td>")
document.writeIn("            <td style="">Vegetable </td>")
document.writeIn("            <td style="">Reduce lightning damage</td>")
document.writeIn("            <td style="">-17%</td>")
document.writeIn("            <td style="">-26%</td>")
document.writeIn("            <td style="">-34％</td>")
document.writeIn("            <td style="">-44%</td>")
document.writeIn("            <td style="">-52%</td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_25">		<td style="">Burdock </td>")
document.writeIn("            <td style="">Vegetable </td>")
document.writeIn("            <td style="">Decrease the duration of Abnormal Status</td>")
document.writeIn("            <td style="">-23%</td>")
document.writeIn("            <td style="">-35%</td>")
document.writeIn("            <td style="">-46％</td>")
document.writeIn("            <td style="">-58%</td>")
document.writeIn("            <td style="">-70%</td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_26">		<td style="">Beets </td>")
document.writeIn("            <td style="">Vegetable 、Seasoning </td>")
document.writeIn("            <td style="">Increase Food Effects</td>")
document.writeIn("            <td style="">+3%</td>")
document.writeIn("            <td style="">+4%</td>")
document.writeIn("            <td style="">+6%</td>")
document.writeIn("            <td style="">+7%</td>")
document.writeIn("            <td style="">+9%</td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_27">		<td style="">Cucumber </td>")
document.writeIn("            <td style="">Vegetable </td>")
document.writeIn("            <td style="">Reduce MP Damage when restrained</td>")
document.writeIn("            <td style="">-12%</td>")
document.writeIn("            <td style="">-19%</td>")
document.writeIn("            <td style="">-25%</td>")
document.writeIn("            <td style="">-31％</td>")
document.writeIn("            <td style="">-38%</td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_28">		<td style="">Turnip </td>")
document.writeIn("            <td style="">Vegetable </td>")
document.writeIn("            <td style="">Increase Casting Speed when MP is depleted</td>")
document.writeIn("            <td style="">+23%</td>")
document.writeIn("            <td style="">+35%</td>")
document.writeIn("            <td style="">+46%</td>")
document.writeIn("            <td style="">+58%</td>")
document.writeIn("            <td style="">+70%</td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_29">		<td style="">Corn </td>")
document.writeIn("            <td style="">Grain 、Vegetable </td>")
document.writeIn("            <td style="">Slow down chest reel speed</td>")
document.writeIn("            <td style="">-14%</td>")
document.writeIn("            <td style="">-22％</td>")
document.writeIn("            <td style="">-29%</td>")
document.writeIn("            <td style="">-36%</td>")
document.writeIn("            <td style="">-44%</td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_30">		<td style="">Onion </td>")
document.writeIn("            <td style="">Vegetable </td>")
document.writeIn("            <td style="">Resist Abnormal Effect</td>")
document.writeIn("            <td style="">+10%</td>")
document.writeIn("            <td style="">+15%</td>")
document.writeIn("            <td style="">+20%</td>")
document.writeIn("            <td style="">+25%</td>")
document.writeIn("            <td style="">+30%</td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_31">		<td style="">Eggplant </td>")
document.writeIn("            <td style="">Vegetable </td>")
document.writeIn("            <td style="">Reduce Fire Damage</td>")
document.writeIn("            <td style="">-17％</td>")
document.writeIn("            <td style="">-26%</td>")
document.writeIn("            <td style="">-34%</td>")
document.writeIn("            <td style="">-44%</td>")
document.writeIn("            <td style="">-52%</td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_32">		<td style="">Garlic </td>")
document.writeIn("            <td style="">Seasoning </td>")
document.writeIn("            <td style="">Calms down Reduce Mana lost when chanting</td>")
document.writeIn("            <td style="">-6%</td>")
document.writeIn("            <td style="">-10%</td>")
document.writeIn("            <td style="">-13%</td>")
document.writeIn("            <td style="">-16%</td>")
document.writeIn("            <td style="">-20%</td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_33">		<td style="">Broccoli&ZeroWidthSpace;</td>")
document.writeIn("            <td style="">Vegetable </td>")
document.writeIn("            <td style="">Resist MP Gauge break</td>")
document.writeIn("            <td style="">+23%</td>")
document.writeIn("            <td style="">+35％</td>")
document.writeIn("            <td style="">+46%</td>")
document.writeIn("            <td style="">+58%</td>")
document.writeIn("            <td style="">+70%</td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_34">		<td style="">Noel Egg </td>")
document.writeIn("            <td style="">Egg </td>")
document.writeIn("            <td style="">Increase chanting speed +<br><span style="color: #F54738;">Easier to escape when restrained</span>-</td>")
document.writeIn("            <td style="">+20%<br><span style="color: #F54738;">-16%</span></td>")
document.writeIn("            <td style="">+30%<br><span style="color: #F54738;">-24%</span></td>")
document.writeIn("            <td style="">+40%<br><span style="color: #F54738;">-33%</span></td>")
document.writeIn("            <td style="">+50%<br><span style="color: #F54738;">-41%</span></td>")
document.writeIn("            <td style="">+60%<br><span style="color: #F54738;">-49%</span></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_35">		<td style="">Livestock Egg </td>")
document.writeIn("            <td style="">Egg </td>")
document.writeIn("            <td style="">Increase chanting speed +</td>")
document.writeIn("            <td style="">+15%</td>")
document.writeIn("            <td style="">+22%</td>")
document.writeIn("            <td style="">+30%</td>")
document.writeIn("            <td style="">+37%</td>")
document.writeIn("            <td style="">+45%</td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_36">		<td style="">Mushroom </td>")
document.writeIn("            <td style="">Mushroom </td>")
document.writeIn("            <td style="">Random Effect</td>")
document.writeIn("            <td style="">+22%</td>")
document.writeIn("            <td style="">+33%</td>")
document.writeIn("            <td style="">+44%</td>")
document.writeIn("            <td style="">+55%</td>")
document.writeIn("            <td style="">+66%</td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_37">		<td style="">Spotted Mushroom</td>")
document.writeIn("            <td style="">Mushroom</td>")
document.writeIn("            <td style="">Random Effect <br><span style="color: #F54738;">Resist Abnormal Effect</span><br><span style="color: #F54738;">Easier to escape when restrained</span><br><span style="color: #F54738;">Resist smoke</span></td>")
document.writeIn("            <td style="">+46%<br><span style="color: #F54738;">-12%</span><br><span style="color: #F54738;">-9%</span><br><span style="color: #F54738;">+8%</span></td>")
document.writeIn("            <td style="">+70%<br><span style="color: #F54738;">-18%</span><br><span style="color: #F54738;">-14%</span><br><span style="color: #F54738;">+13%</span></td>")
document.writeIn("            <td style="">+93%<br><span style="color: #F54738;">-25%</span><br><span style="color: #F54738;">-19%</span><br><span style="color: #F54738;">+17%</span></td>")
document.writeIn("            <td style="">+116%<br><span style="color: #F54738;">-31%</span><br><span style="color: #F54738;">-24%</span><br><span style="color: #F54738;">+22%</span></td>")
document.writeIn("            <td style="">+140%<br><span style="color: #F54738;">-37%</span><br><span style="color: #F54738;">-29%</span><br><span style="color: #F54738;">+26%</span></td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">5</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_38">		<td style="">Rock Salt </td>")
document.writeIn("            <td style="">Seasoning </td>")
document.writeIn("            <td style="">Increase Food Effects</td>")
document.writeIn("            <td style="">+6%</td>")
document.writeIn("            <td style="">+10%</td>")
document.writeIn("            <td style="">+13%</td>")
document.writeIn("            <td style="">+16%</td>")
document.writeIn("            <td style="">+20%</td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style="">10</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_39">		<td style="">Pepper </td>")
document.writeIn("            <td style="">Seasoning </td>")
document.writeIn("            <td style="">Easier to escape when restrained</td>")
document.writeIn("            <td style="">+13％</td>")
document.writeIn("            <td style="">+20%</td>")
document.writeIn("            <td style="">+26%</td>")
document.writeIn("            <td style="">+33%</td>")
document.writeIn("            <td style="">+44%</td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_40">		<td style="">Carrot </td>")
document.writeIn("            <td style="">Vegetable </td>")
document.writeIn("            <td style="">Makes it harder to slip</td>")
document.writeIn("            <td style="">-23％</td>")
document.writeIn("            <td style="">-35%</td>")
document.writeIn("            <td style="">-46%</td>")
document.writeIn("            <td style="">-58%</td>")
document.writeIn("            <td style="">-70%</td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_41">		<td style="">Poisonous Seed </td>")
document.writeIn("            <td style="">Other </td>")
document.writeIn("            <td style="">Resist Abnormal Effect</td>")
document.writeIn("            <td style="">+4%</td>")
document.writeIn("            <td style="">+5％</td>")
document.writeIn("            <td style="">+8%</td>")
document.writeIn("            <td style="">+9%</td>")
document.writeIn("            <td style="">+11%</td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style=""></td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_42">		<td style="">Monster's Skin </td>")
document.writeIn("            <td style="">Other </td>")
document.writeIn("            <td style="text-align:center;">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_43">		<td style="">Glass Shard </td>")
document.writeIn("            <td style="">Other </td>")
document.writeIn("            <td style="text-align:center;">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_44">		<td style="">Rosemary</td>")
document.writeIn("            <td style="">Herb</td>")
document.writeIn("            <td style="">Make MP gauge sturdy</td>")
document.writeIn("            <td style="">+13%</td>")
document.writeIn("            <td style="">+20%</td>")
document.writeIn("            <td style="">+26%</td>")
document.writeIn("            <td style="">+33%</td>")
document.writeIn("            <td style="">+40%</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_45">		<td style="">Basil</td>")
document.writeIn("            <td style="">Herb</td>")
document.writeIn("            <td style="">Resist abnormal effects</td>")
document.writeIn("            <td style="">+11%</td>")
document.writeIn("            <td style="">+16%</td>")
document.writeIn("            <td style="">+22%</td>")
document.writeIn("            <td style="">+28%</td>")
document.writeIn("            <td style="">+34%</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_46">		<td style="">Lemongrass</td>")
document.writeIn("            <td style="">Herb</td>")
document.writeIn("            <td style="">damage when restrained</td>")
document.writeIn("            <td style="">-10％</td>")
document.writeIn("            <td style="">-16％</td>")
document.writeIn("            <td style="">-22％</td>")
document.writeIn("            <td style="">-27％</td>")
document.writeIn("            <td style="">-33％</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_47">		<td style="">Sage</td>")
document.writeIn("            <td style="">Herb</td>")
document.writeIn("            <td style="">time of abnormal effects</td>")
document.writeIn("            <td style="">-12％</td>")
document.writeIn("            <td style="">-17％</td>")
document.writeIn("            <td style="">-21％</td>")
document.writeIn("            <td style="">-25％</td>")
document.writeIn("            <td style="">-29％</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_48">		<td style="">Rose Geranium</td>")
document.writeIn("            <td style="">Herb</td>")
document.writeIn("            <td style=""><span style="color: #F54738;">Reduce mana lost when taking damage during chanting</span><br>Resist smoke</td>")
document.writeIn("            <td style=""><span style="color: #F54738;">+9%</span><br>-18％</td>")
document.writeIn("            <td style=""><span style="color: #F54738;">+14%</span><br>-27％</td>")
document.writeIn("            <td style=""><span style="color: #F54738;">+19%</span><br>-36％</td>")
document.writeIn("            <td style=""><span style="color: #F54738;">+24%</span><br>-45％</td>")
document.writeIn("            <td style=""><span style="color: #F54738;">+29%</span><br>-54％</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_49">		<td style="">Peppermint</td>")
document.writeIn("            <td style="">Herb</td>")
document.writeIn("            <td style=""><span style="color: #F54738;">Reduce slipperiness</span><br>Increases the amount of mana you can steal from using weak attacks</td>")
document.writeIn("            <td style=""><span style="color: #F54738;">+19％</span><br>+20％</td>")
document.writeIn("            <td style=""><span style="color: #F54738;">+29％</span><br>+30％</td>")
document.writeIn("            <td style=""><span style="color: #F54738;">+39％</span><br>+40％</td>")
document.writeIn("            <td style=""><span style="color: #F54738;">+49％</span><br>+50％</td>")
document.writeIn("            <td style=""><span style="color: #F54738;">+59%</span><br>+60％</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_50">		<td style="">Catnip</td>")
document.writeIn("            <td style="">Herb</td>")
document.writeIn("            <td style="">Increase casting speed when MP is depleted<br><span style="color: #F54738;">Easier to escape when restrained</span></td>")
document.writeIn("            <td style="">+20%<br><span style="color: #F54738;">-11%</span></td>")
document.writeIn("            <td style="">+30%<br><span style="color: #F54738;">-17%</span></td>")
document.writeIn("            <td style="">+40%<br><span style="color: #F54738;">-23%</span></td>")
document.writeIn("            <td style="">+50%<br><span style="color: #F54738;">-29%</span></td>")
document.writeIn("            <td style="">+60%<br><span style="color: #F54738;">-34%</span></td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_51">		<td style="">Chamomile</td>")
document.writeIn("            <td style="">Herb</td>")
document.writeIn("            <td style="">Reduce fire damage<br>Reduce thunder damage<br>Reduce frozen damage</td>")
document.writeIn("            <td style="">-6％<br>-6％<br>-6％</td>")
document.writeIn("            <td style="">-9％<br>-9％<br>-9％</td>")
document.writeIn("            <td style="">-12％<br>-12％<br>-12％</td>")
document.writeIn("            <td style="">-15％<br>-15％<br>-15％</td>")
document.writeIn("            <td style="">-19％<br>-19％<br>-19％</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_52">		<td style="">Coal</td>")
document.writeIn("            <td style="">Other</td>")
document.writeIn("            <td style="text-align:center;">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">30</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_53">		<td style="">Quartz</td>")
document.writeIn("            <td style="">Other</td>")
document.writeIn("            <td style="text-align:center;">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">20</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_54">		<td style="">Amethyst</td>")
document.writeIn("            <td style="">Other</td>")
document.writeIn("            <td style="text-align:center;">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">10</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_55">		<td style="">Steel</td>")
document.writeIn("            <td style="">Other</td>")
document.writeIn("            <td style="text-align:center;">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">10</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_56">		<td style="">Chrome</td>")
document.writeIn("            <td style="">Other</td>")
document.writeIn("            <td style="text-align:center;">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">10</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_57">		<td style="">Sulfur</td>")
document.writeIn("            <td style="">Other</td>")
document.writeIn("            <td style="text-align:center;">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">10</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_58">		<td style="">Niter</td>")
document.writeIn("            <td style="">Other</td>")
document.writeIn("            <td style="text-align:center;">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">10</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_59">		<td style="">Gold ore</td>")
document.writeIn("            <td style="">Other</td>")
document.writeIn("            <td style="text-align:center;">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">10</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_60">		<td style="">Red Beryl</td>")
document.writeIn("            <td style="">Other</td>")
document.writeIn("            <td style="text-align:center;">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">10</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_61">		<td style="">Sapphire</td>")
document.writeIn("            <td style="">Other</td>")
document.writeIn("            <td style="text-align:center;">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">10</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_62">		<td style="">Topaz</td>")
document.writeIn("            <td style="">Other</td>")
document.writeIn("            <td style="text-align:center;">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">10</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_63">		<td style="">Morganite</td>")
document.writeIn("            <td style="">Other</td>")
document.writeIn("            <td style="text-align:center;">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">10</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_64">		<td style="">Nekoite</td>")
document.writeIn("            <td style="">Other</td>")
document.writeIn("            <td style="text-align:center;">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">10</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_65">		<td style="">Wood</td>")
document.writeIn("            <td style="">Other</td>")
document.writeIn("            <td style="text-align:center;">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">30</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_66">		<td style="">Stone</td>")
document.writeIn("            <td style="">Other</td>")
document.writeIn("            <td style="text-align:center;">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">30</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_67">		<td style="">Fake Slime Egg</td>")
document.writeIn("            <td style="">Other</td>")
document.writeIn("            <td style="text-align:center;">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">5</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_68">		<td style="">Black Cotton Spores</td>")
document.writeIn("            <td style="">Other</td>")
document.writeIn("            <td style="text-align:center;">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">5</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_69">		<td style="">Golem’s Right Hand</td>")
document.writeIn("            <td style="">Other</td>")
document.writeIn("            <td style="text-align:center;">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">5</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_70">		<td style="">Urchin Spine</td>")
document.writeIn("            <td style="">Other</td>")
document.writeIn("            <td style="text-align:center;">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">5</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_71">		<td style="">Snake Skin</td>")
document.writeIn("            <td style="">Other</td>")
document.writeIn("            <td style="text-align:center;">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">5</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_72">		<td style="">Lizard Tail</td>")
document.writeIn("            <td style="">Other</td>")
document.writeIn("            <td style="text-align:center;">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">5</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_73">		<td style="">Round Sponge Shell</td>")
document.writeIn("            <td style="">Other</td>")
document.writeIn("            <td style="text-align:center;">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">5</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_74">		<td style="">Empty Bottle</td>")
document.writeIn("            <td style="">Other</td>")
document.writeIn("            <td style="text-align:center;">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">1</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_75">		<td style="">Lunch Box</td>")
document.writeIn("            <td style="">Other</td>")
document.writeIn("            <td style="text-align:center;">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">1</td></tr>")
document.writeIn("    <tr class="atwiki_tr_even atwiki_tr_76">		<td style="">Merchant's Bell</td>")
document.writeIn("            <td style="">Other</td>")
document.writeIn("            <td style="text-align:center;">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">1</td></tr>")
document.writeIn("    <tr class="atwiki_tr_odd atwiki_tr_77">		<td style="">Bag Expansion Kit</td>")
document.writeIn("            <td style="">Enhancement</td>")
document.writeIn("            <td style="">Increase max item that can be carried inside inventory。</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="text-align:center;" colspan="5">-</td>")
document.writeIn("            <td style="">-</td></tr>")
document.writeIn("    </tbody></table>")
